org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Fabric Loom is not fully compatible with Gradle configuration cache.
org.gradle.configuration-cache=false

# Fabric 26.3
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21
fabric_api_version=0.161.0+26.3

# Mod
mod_id=entity_collision_optimizer
mod_name=Entity Collision Optimizer
mod_version=1.0.0-mc26.3-alpha.7
maven_group=org.edtp
archives_base_name=entity_collision_optimizer
